{% set name = "apache-airflow-providers-dbt-cloud" %}
{% set version = "3.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_dbt_cloud-{{ version }}.tar.gz
  sha256: 032c6eb2bf3e861aec72b754e80b190916a5f8c501d4188f481b5dd85e6bcd52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.9.2
    - apache-airflow-providers-http
    - apache-airflow >=2.8.0
    - asgiref

test:
  imports:
    - airflow.providers.dbt.cloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-dbt-cloud for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/dbt/cloud/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-dbt-cloud/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
