{% set name = "apache-airflow-providers-dbt-cloud" %}
{% set version = "3.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_dbt_cloud-{{ version }}.tar.gz
  sha256: 4dc03d2b0149e790e53b73e6dba307d56200d33e58f39d9eba034139cbec6b15

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.10.1
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3.9.2
    - apache-airflow-providers-http
    - apache-airflow >=2.8.0
    - asgiref >=2.3.0

test:
  imports:
    - airflow.providers.dbt.cloud
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-dbt-cloud for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/dbt/cloud/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-dbt-cloud/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
