{% set name = "apache-airflow-providers-dbt-cloud" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_dbt_cloud-{{ version }}.tar.gz
  sha256: ef063e32bd546c7d6fe543c1f6d35ad5e21ce1b70372beacd3bcc7295c627d5f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.9.2
    - apache-airflow-providers-http
    - apache-airflow >=2.6.0
    - asgiref

test:
  imports:
    - airflow.providers.dbt.cloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-dbt-cloud for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/dbt/cloud/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-dbt-cloud/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
