{% set name = "apache-airflow-providers-dbt-cloud" %}
{% set version = "3.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-dbt-cloud-{{ version }}.tar.gz
  sha256: 7a9945399054588c129bc828af22eeb5267cf5ef6f20c7c4db913d2709b3a491

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=67.2.0,<68.0.0
    - pip
  run:
    - python >=3.8
    - aiohttp
    - apache-airflow-providers-http
    - apache-airflow >=2.4.0
    - asgiref

test:
  imports:
    - airflow.providers.dbt.cloud
    - airflow.providers.dbt.cloud.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-dbt-cloud package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-dbt-cloud/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
