{% set name = "apache-airflow-providers-dbt-cloud" %}
{% set version = "4.5.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_dbt_cloud-{{ version }}.tar.gz
  sha256: a4b095c338abe2fd41313b21afe163bbaf1205b03e5b1dcf0b577574d1a2916d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - apache-airflow-providers-common-compat >=1.8.0
    - apache-airflow-providers-http
    - asgiref >=2.3.0
    - aiohttp >=3.9.2
    - tenacity >=8.3.0

test:
  imports:
    - airflow.providers.dbt.cloud
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-dbt-cloud for Apache Airflow
  license: Apache-2.0
  license_file: 
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-dbt-cloud/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
